# Generated by Django 3.1.7 on 2021-03-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artice',
            new_name='Article',
        ),
    ]
